print("Programming Languages:")
print("1. Python")
print("2. JavaScript")
print("3. Java")
print("4. C and C++")
print("5. Go")
print("6. Swift")
print("7. Kotlin")
print("8. C#")
print("9. Rust")
print("10. PHP")